Modify script (#3604)

diff --git a/src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx b/src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx
--- a/src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx
+++ b/src/commcare_cloud/ansible/roles/nginx/files/dynamic_cfg_change_nginx
@@ -17,14 +17,16 @@ Option:
 }
 
 
- change_limits() {
+change_limits() {
     cfg_file=$1
     zone=$2
-    var=$3
-    limit=$4
-    old_config=`grep -E "^limit_req_zone.*${zone}" ${cfg_file}`
-    new_config="limit_req_zone \$${var} zone=${zone}:10m rate=${limit}r/s;"
-    sed -i "s[$old_config[$new_config[g" ${cfg_file}
+    bucket_name=$3
+    rate_limit=$4
+    old_config=`grep -E "^limit_req_zone .*${bucket_name}.*${zone}" ${cfg_file}`
+    if [[ ! -z "$old_config" ]]; then
+      new_config="limit_req_zone \$${bucket_name} zone=${zone}:10m rate=${rate_limit}r/s;"
+      sed -i "s[$old_config[$new_config[g" ${cfg_file}
+    fi
 }
 
 main() {
@@ -65,38 +67,46 @@ main() {
 
 
     cfg_file='/etc/nginx/sites-available/icds_cas_commcare'
+    
+    /usr/sbin/service nginx configtest
+    if [ $? -eq 0 ]; then
+        cp $cfg_file /tmp
+    else
+        echo "Nginx conf is not correct. Manual intervention is required."
+        exit 1
 
     if [[ "$incremental_restore" ]]; then
             change_limits "$cfg_file" "incremental_restore" "incremental_sync" "$incremental_restore"
     fi
 
     if [[ "$overall_restore" ]]; then
-            change_limits "$cfg_file" "overall_restore" "limit_bucket" "$overall_restore"
+            change_limits "$cfg_file" "overall_restore" "global_limit" "$overall_restore"
     fi
 
     if [[ "$submission" ]]; then
-            change_limits "$cfg_file" "submission" "limit_bucket" "$submission"
+            change_limits "$cfg_file" "submission" "global_limit" "$submission"
     fi
 
     if [[ "$app_download" ]]; then
-            change_limits "$cfg_file" "app_download" "limit_bucket" "$app_download"
+            change_limits "$cfg_file" "app_download" "global_limit" "$app_download"
     fi
 
     if [[ "$multimedia" ]]; then
-           change_limits "$cfg_file" "multimedia" "limit_bucket" "$multimedia"
+           change_limits "$cfg_file" "multimedia" "global_limit" "$multimedia"
     fi
 
     if [[ "$default_server" ]]; then
-             change_limits "$cfg_file" "server_name" "limit_bucket" "$default_server"
+             change_limits "$cfg_file" "server_name" "global_limit" "$default_server"
     fi
 
-    service nginx configtest
+    /usr/sbin/service nginx configtest
 
     if [ $? -eq 0 ]; then
             systemctl reload nginx
     else
+        cp /tmp/icds_cas_commcare $cfg_file
 	    echo "Nginx conf is not correct. Manual intervention is required."
-            exit 1
+        exit 1
     fi
 }
 
